DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS ages;



CREATE TABLE ages (
  id SERIAL PRIMARY KEY,
  name INTEGER NOT NULL UNIQUE
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  age INTEGER NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT false,
  FOREIGN KEY (age) REFERENCES ages (id)
);
